import type { Profile, ResolvedTokens, TimelineState } from '@/types'

/** Build the canonical token JSON export. */
export function exportTokenJSON(
  profile: Profile,
  tokens: ResolvedTokens,
  theme: string,
): string {
  const payload = {
    $schema: 'https://nezam.design/schema/tokens-v2.json',
    meta: {
      name: profile.name,
      profile: profile.id,
      theme,
      generatedAt: new Date().toISOString(),
    },
    color: {
      brand: tokens.brand,
      brandHover: tokens.brandHover,
      brandSubtle: tokens.brandSubtle,
      onBrand: tokens.onBrand,
      accent: tokens.accent,
      bg: tokens.bg,
      surface: tokens.surface,
      elevated: tokens.elevated,
      text: tokens.text,
      textMuted: tokens.textMuted,
      textSubtle: tokens.textSubtle,
      border: tokens.border,
      borderStrong: tokens.borderStrong,
      success: tokens.success,
      warning: tokens.warning,
      danger: tokens.danger,
      info: tokens.info,
    },
    shape: {
      radius: tokens.radius,
      density: tokens.density,
      shadow: tokens.shadow,
    },
    type: {
      fontSans: tokens.fontSans,
      fontDisplay: tokens.fontDisplay,
    },
  }
  return JSON.stringify(payload, null, 2)
}

/** Build a human-readable DESIGN.md contract. */
export function exportDesignMd(
  profile: Profile,
  tokens: ResolvedTokens,
  theme: string,
): string {
  const row = (k: string, v: string) => `| \`${k}\` | ${v} | ![](https://singlecolorimage.com/get/${v.replace('#', '')}/16x16) |`
  const isHex = (v: string) => /^#/.test(v)
  const colorRows = (
    [
      ['brand', tokens.brand],
      ['brandHover', tokens.brandHover],
      ['accent', tokens.accent],
      ['bg', tokens.bg],
      ['surface', tokens.surface],
      ['text', tokens.text],
      ['textMuted', tokens.textMuted],
      ['border', tokens.border],
      ['success', tokens.success],
      ['warning', tokens.warning],
      ['danger', tokens.danger],
      ['info', tokens.info],
    ] as Array<[string, string]>
  )
    .map(([k, v]) => (isHex(v) ? row(k, v) : `| \`${k}\` | ${v} | — |`))
    .join('\n')

  return `# DESIGN.md — ${profile.name}

> Generated by NEZAM Design Hub · ${new Date().toISOString().slice(0, 10)}

**Personality.** ${profile.personality}

## Theme
- Mode: \`${theme}\`
- Profile: \`${profile.id}\`

## Color tokens

| Token | Value | Swatch |
|-------|-------|--------|
${colorRows}

## Shape

- **Radius base:** \`${tokens.radius}px\`
- **Density:** \`${tokens.density}\`
- **Elevation:** \`${tokens.shadow}\`

## Typography

- **Sans / UI:** \`${tokens.fontSans}\`
- **Display / Headings:** \`${tokens.fontDisplay}\`

## Usage

All components must consume \`var(--n-*)\` custom properties. Never hardcode a
raw color, radius, or shadow — the token layer is the single source of truth.
`
}

/** Generate ready-to-paste GSAP code from the animation timeline. */
export function exportGsapCode(timeline: TimelineState): string {
  const PROP_MAP: Record<string, string> = {
    opacity: 'autoAlpha',
    y: 'y',
    x: 'x',
    scale: 'scale',
    rotate: 'rotation',
    blur: 'filter',
  }

  const blocks = timeline.tracks
    .map((track) => {
      const sel =
        track.target === 'all' ? '[data-anim]' : `[data-anim="${track.target}"]`
      const fromVars: string[] = []
      const toVars: string[] = []
      for (const kf of track.keyframes) {
        const prop = PROP_MAP[kf.property]
        if (kf.property === 'blur') {
          fromVars.push(`filter: 'blur(${kf.from}px)'`)
          toVars.push(`filter: 'blur(${kf.to}px)'`)
        } else {
          fromVars.push(`${prop}: ${kf.from}`)
          toVars.push(`${prop}: ${kf.to}`)
        }
      }
      const startAt = Math.min(...track.keyframes.map((k) => k.at), 0)
      return `  tl.fromTo(
    '${sel}',
    { ${fromVars.join(', ')} },
    {
      ${toVars.join(',\n      ')},
      duration: ${timeline.duration.toFixed(2)},
      stagger: ${timeline.stagger},
      ease: 'power3.out',
    },
    ${startAt.toFixed(2)},
  )`
    })
    .join('\n')

  const trigger = timeline.scrollTrigger
    ? `
  scrollTrigger: {
    trigger: '[data-anim-root]',
    start: 'top 75%',
    toggleActions: 'play none none reverse',
  },`
    : ''

  return `import { gsap } from 'gsap'
${timeline.scrollTrigger ? "import { ScrollTrigger } from 'gsap/ScrollTrigger'\n\ngsap.registerPlugin(ScrollTrigger)\n" : ''}
// NEZAM Design Hub — generated animation timeline
export function playEntrance() {
  const tl = gsap.timeline({
    defaults: { ease: 'power3.out' },${trigger}
  })

${blocks}

  return tl
}
`
}

/** Trigger a browser download for a generated file. */
export function downloadFile(filename: string, content: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
