'use client'

import {
  Home,
  FileText,
  Info,
  DollarSign,
  Mail,
  Key,
  Sparkles,
  Lock,
  LockOpen,
  LayoutDashboard,
  FilePen,
  Image,
  Users,
  User,
  Settings,
  ChartBar,
  FolderOpen,
  Folder,
  SquareCheckBig,
  Inbox,
  Calendar,
  Bell,
  Briefcase,
  CreditCard,
  Building2,
  Plug,
  Bookmark,
  BookOpen,
  Tag,
  Wrench,
  ClipboardPenLine,
  LayoutGrid,
  ShoppingBag,
  ShoppingCart,
  Heart,
  Package,
  Zap,
  Shield,
  Compass,
  CircleHelp,
  UserPlus,
  CircleCheck,
  Database,
  FilePlus2,
  Network,
  Palette,
  Eye,
  EyeOff,
  Puzzle,
  Monitor,
  Tablet,
  Smartphone,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Trash2,
  Pencil,
  ArrowUpRight,
  Ellipsis,
  Moon,
  Sun,
  PanelRight,
  Download,
  X,
  CornerDownRight,
  Search,
  Copy,
  SquareArrowOutUpRight,
  CircleAlert,
  CircleX,
  Star,
  Globe,
  Link,
  Hash,
  Droplet,
  Type,
  ArrowRightLeft,
  Circle,
  Layers,
  Square,
  MousePointer,
  AlignLeft,
  Ruler,
  SlidersVertical,
  Shapes,
  Grid,
  Box,
  FileCode,
  Columns,
  SlidersHorizontal,
  ToggleLeft,
  MessageSquare,
  Navigation,
  PanelLeft,
  ListFilter,
  type LucideIcon,
} from 'lucide-react'

import React from 'react'

export const ICON_MAP: Record<string, LucideIcon> = {
  Home,
  FileText,
  Info,
  DollarSign,
  Mail,
  Key,
  Sparkles,
  Lock,
  LockOpen,
  LayoutDashboard,
  FilePen,
  Image,
  Users,
  User,
  Settings,
  ChartBar,
  FolderOpen,
  Folder,
  SquareCheckBig,
  Inbox,
  Calendar,
  Bell,
  Briefcase,
  CreditCard,
  Building2,
  Plug,
  Bookmark,
  BookOpen,
  Tag,
  Wrench,
  ClipboardPenLine,
  LayoutGrid,
  ShoppingBag,
  ShoppingCart,
  Heart,
  Package,
  Zap,
  Shield,
  Compass,
  CircleHelp,
  UserPlus,
  CircleCheck,
  Database,
  FilePlus2,
  Network,
  Palette,
  Eye,
  EyeOff,
  Puzzle,
  Monitor,
  Tablet,
  Smartphone,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Trash2,
  Pencil,
  ArrowUpRight,
  Ellipsis,
  Moon,
  Sun,
  PanelRight,
  Download,
  X,
  CornerDownRight,
  Search,
  Copy,
  SquareArrowOutUpRight,
  CircleAlert,
  CircleX,
  Star,
  Globe,
  Link,
  Hash,
  Droplet,
  Type,
  ArrowRightLeft,
  Circle,
  Layers,
  Square,
  MousePointer,
  AlignLeft,
  Ruler,
  SlidersVertical,
  Shapes,
  Grid,
  Box,
  FileCode,
  Columns,
  SlidersHorizontal,
  ToggleLeft,
  MessageSquare,
  Navigation,
  PanelLeft,
  ListFilter,
}

export const PAGE_ICON_NAMES: string[] = [
  'FileText', 'FolderOpen', 'Home', 'Settings', 'User', 'CreditCard',
  'ChartBar', 'FilePen', 'Key', 'Mail', 'BookOpen', 'Lock',
  'Calendar', 'DollarSign', 'Zap', 'SquareCheckBig', 'Folder', 'Bell',
  'Image', 'Users', 'Inbox', 'Tag', 'Plug', 'LayoutDashboard',
  'ClipboardPenLine', 'Wrench', 'Shield', 'Compass', 'Heart', 'ShoppingBag',
]

interface IconRendererProps {
  name: string
  size?: number
  className?: string
  strokeWidth?: number
  style?: React.CSSProperties
}

export function IconRenderer({ name, size = 16, className, strokeWidth = 1.5, style }: IconRendererProps) {
  const IconComponent = ICON_MAP[name]
  if (!IconComponent) {
    return React.createElement(FileText, { size, className, strokeWidth, style })
  }
  return React.createElement(IconComponent, { size, className, strokeWidth, style })
}
