// ─────────────────────────────────────────────────────────────────────────────
// NEZAM Layout Designer — Shadcn/Radix Component Library
// ─────────────────────────────────────────────────────────────────────────────

import type { LibraryBlock } from './types'

export const COMPONENT_LIBRARY: LibraryBlock[] = [
  // ── NAVIGATION ────────────────────────────────────────────────────────────

  {
    id: 'navbar-top',
    name: 'Top Navbar',
    description: 'Horizontal top navigation with logo, links, and CTA',
    category: 'navigation',
    shadcnComponents: ['NavigationMenu', 'Button', 'Sheet'],
    radixPrimitives: ['NavigationMenu'],
    canvasHeight: 64,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['nav', 'header', 'menu'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Logo + links + CTA' },
      { id: 'centered', label: 'Centered', description: 'Centered logo with links on both sides' },
      { id: 'mega-menu', label: 'Mega Menu', description: 'Dropdown with rich content panels' },
    ],
  },
  {
    id: 'sidebar-nav',
    name: 'Sidebar Navigation',
    description: 'Vertical sidebar with grouped nav items and collapse',
    category: 'navigation',
    shadcnComponents: ['ScrollArea', 'Collapsible', 'Badge'],
    radixPrimitives: ['Collapsible'],
    canvasHeight: 500,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['sidebar', 'nav', 'dashboard'],
    variants: [
      { id: 'full', label: 'Full Width', description: 'Expanded sidebar with labels' },
      { id: 'icon-only', label: 'Icon Only', description: 'Collapsed icon-only rail' },
      { id: 'grouped', label: 'Grouped', description: 'Sections with headings' },
    ],
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    description: 'Hierarchical page trail with dropdown for overflow',
    category: 'navigation',
    shadcnComponents: ['Breadcrumb', 'DropdownMenu'],
    radixPrimitives: ['DropdownMenu'],
    canvasHeight: 40,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['breadcrumb', 'nav', 'trail'],
    variants: [
      { id: 'default', label: 'Default', description: 'Slash-separated path' },
      { id: 'chevron', label: 'Chevron', description: 'Chevron separators' },
      { id: 'collapsed', label: 'Collapsed', description: 'Ellipsis for long paths' },
    ],
  },
  {
    id: 'tabs-nav',
    name: 'Tab Navigation',
    description: 'Horizontal tab bar for content switching',
    category: 'navigation',
    shadcnComponents: ['Tabs', 'TabsList', 'TabsTrigger'],
    radixPrimitives: ['Tabs'],
    canvasHeight: 48,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['tabs', 'nav', 'switch'],
    variants: [
      { id: 'underline', label: 'Underline', description: 'Active tab with underline' },
      { id: 'pill', label: 'Pill', description: 'Filled pill active state' },
      { id: 'card', label: 'Card', description: 'Card-style tabs' },
    ],
  },
  {
    id: 'pagination',
    name: 'Pagination',
    description: 'Page navigation with prev/next and number buttons',
    category: 'navigation',
    shadcnComponents: ['Pagination', 'PaginationContent', 'PaginationItem'],
    radixPrimitives: [],
    canvasHeight: 48,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['pagination', 'pages', 'nav'],
    variants: [
      { id: 'numbered', label: 'Numbered', description: 'All page numbers' },
      { id: 'simple', label: 'Simple', description: 'Prev / Next only' },
      { id: 'compact', label: 'Compact', description: 'Current / total with arrows' },
    ],
  },

  // ── HERO ──────────────────────────────────────────────────────────────────

  {
    id: 'hero-centered',
    name: 'Centered Hero',
    description: 'Full-width hero with headline, sub, and CTA centered',
    category: 'hero',
    shadcnComponents: ['Button', 'Badge'],
    radixPrimitives: [],
    canvasHeight: 480,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['hero', 'landing', 'headline'],
    variants: [
      { id: 'clean', label: 'Clean', description: 'Text + CTA on plain background' },
      { id: 'gradient', label: 'Gradient', description: 'Gradient background with glow' },
      { id: 'with-image', label: 'With Image', description: 'Centered hero with below-fold image' },
      { id: 'announcement', label: 'Announcement', description: 'Badge pill + headline + CTA' },
    ],
  },
  {
    id: 'hero-split',
    name: 'Split Hero',
    description: 'Two-column hero: text left, visual right',
    category: 'hero',
    shadcnComponents: ['Button', 'AspectRatio', 'Badge'],
    radixPrimitives: ['AspectRatio'],
    canvasHeight: 520,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['hero', 'split', 'two-column'],
    variants: [
      { id: 'text-left', label: 'Text Left', description: 'Text on left, image/video on right' },
      { id: 'text-right', label: 'Text Right', description: 'Image on left, text on right' },
      { id: 'video', label: 'With Video', description: 'Embedded video in right pane' },
    ],
  },
  {
    id: 'hero-fullscreen',
    name: 'Full Screen Hero',
    description: '100vh hero with overlay content and background',
    category: 'hero',
    shadcnComponents: ['Button'],
    radixPrimitives: [],
    canvasHeight: 600,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['hero', 'fullscreen', 'background'],
    variants: [
      { id: 'dark-overlay', label: 'Dark Overlay', description: 'Dark gradient over image' },
      { id: 'video-bg', label: 'Video BG', description: 'Looping video background' },
      { id: 'particles', label: 'Particles', description: 'Animated particle field' },
    ],
  },

  // ── CONTENT ───────────────────────────────────────────────────────────────

  {
    id: 'card-grid',
    name: 'Card Grid',
    description: 'Grid of feature/product/article cards',
    category: 'content',
    shadcnComponents: ['Card', 'CardHeader', 'CardContent', 'CardFooter', 'Badge', 'Button'],
    radixPrimitives: [],
    canvasHeight: 360,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['cards', 'grid', 'features', 'products'],
    variants: [
      { id: 'feature', label: 'Feature Cards', description: 'Icon + title + description' },
      { id: 'product', label: 'Product Cards', description: 'Image + price + add to cart' },
      { id: 'article', label: 'Article Cards', description: 'Thumbnail + meta + title' },
      { id: 'stat', label: 'Stat Cards', description: 'Large number + label + trend' },
      { id: 'pricing', label: 'Pricing Cards', description: 'Plan + features + CTA' },
    ],
  },
  {
    id: 'content-section',
    name: 'Content Section',
    description: 'Rich text section with optional sidebar or image',
    category: 'content',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 320,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['content', 'text', 'article'],
    variants: [
      { id: 'prose', label: 'Prose', description: 'Full-width article-style text' },
      { id: 'two-col', label: 'Two Column', description: 'Content left, sidebar right' },
      { id: 'with-image', label: 'With Image', description: 'Text + adjacent image' },
    ],
  },
  {
    id: 'faq-accordion',
    name: 'FAQ / Accordion',
    description: 'Expandable Q&A sections with animated transitions',
    category: 'content',
    shadcnComponents: ['Accordion', 'AccordionItem', 'AccordionTrigger', 'AccordionContent'],
    radixPrimitives: ['Accordion'],
    canvasHeight: 280,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['faq', 'accordion', 'expandable'],
    variants: [
      { id: 'single', label: 'Single Open', description: 'Only one item open at a time' },
      { id: 'multiple', label: 'Multiple Open', description: 'Multiple items can be open' },
    ],
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
    description: 'Customer quotes with avatar and attribution',
    category: 'content',
    shadcnComponents: ['Card', 'Avatar', 'AvatarImage', 'AvatarFallback'],
    radixPrimitives: ['Avatar'],
    canvasHeight: 300,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['testimonials', 'quotes', 'social-proof'],
    variants: [
      { id: 'grid', label: 'Grid', description: '3-column card grid' },
      { id: 'carousel', label: 'Carousel', description: 'Sliding carousel' },
      { id: 'featured', label: 'Featured', description: 'Large centered quote' },
    ],
  },
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Vertical or horizontal chronological timeline',
    category: 'content',
    shadcnComponents: ['Badge', 'Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 400,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['timeline', 'history', 'steps'],
    variants: [
      { id: 'vertical', label: 'Vertical', description: 'Top-to-bottom with connector line' },
      { id: 'alternating', label: 'Alternating', description: 'Left-right alternating layout' },
    ],
  },
  {
    id: 'team-grid',
    name: 'Team Grid',
    description: 'Team member cards with photo, name, role, and links',
    category: 'content',
    shadcnComponents: ['Card', 'Avatar', 'Button'],
    radixPrimitives: ['Avatar'],
    canvasHeight: 340,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['team', 'people', 'about'],
    variants: [
      { id: 'cards', label: 'Cards', description: 'Photo + bio card' },
      { id: 'minimal', label: 'Minimal', description: 'Photo + name + role' },
    ],
  },
  {
    id: 'cta-banner',
    name: 'CTA Banner',
    description: 'Full-width call-to-action strip with headline and button',
    category: 'content',
    shadcnComponents: ['Button'],
    radixPrimitives: [],
    canvasHeight: 160,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['cta', 'banner', 'conversion'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Text + primary button' },
      { id: 'two-cta', label: 'Two CTAs', description: 'Primary + secondary buttons' },
      { id: 'input-cta', label: 'Email CTA', description: 'Email input + submit' },
    ],
  },
  {
    id: 'logo-bar',
    name: 'Logo Bar',
    description: 'Brand logo strip for partners / clients / integrations',
    category: 'content',
    shadcnComponents: [],
    radixPrimitives: [],
    canvasHeight: 100,
    supportsGrid: true,
    supportsRTL: false,
    tags: ['logos', 'brands', 'partners', 'trust'],
    variants: [
      { id: 'static', label: 'Static', description: 'Fixed grid of logos' },
      { id: 'marquee', label: 'Marquee', description: 'Infinite scrolling logos' },
    ],
  },
  {
    id: 'stats-bar',
    name: 'Stats Bar',
    description: 'Horizontal bar of key metrics / numbers',
    category: 'content',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 140,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['stats', 'metrics', 'numbers'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Number + label' },
      { id: 'with-icon', label: 'With Icon', description: 'Icon + number + label' },
      { id: 'animated', label: 'Animated', description: 'Count-up animation on scroll' },
    ],
  },

  // ── DATA ──────────────────────────────────────────────────────────────────

  {
    id: 'data-table',
    name: 'Data Table',
    description: 'Sortable, filterable data table with row actions',
    category: 'data',
    shadcnComponents: ['Table', 'TableHeader', 'TableBody', 'TableRow', 'TableCell', 'Checkbox', 'Button', 'DropdownMenu', 'Input'],
    radixPrimitives: ['DropdownMenu', 'Checkbox'],
    canvasHeight: 440,
    supportsGrid: false,
    supportsRTL: false,
    tags: ['table', 'data', 'list'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Basic rows and columns' },
      { id: 'selectable', label: 'Selectable', description: 'Checkbox selection + bulk actions' },
      { id: 'expandable', label: 'Expandable', description: 'Expandable row details' },
    ],
  },
  {
    id: 'dashboard-grid',
    name: 'Dashboard Grid',
    description: 'KPI card grid with charts for admin dashboards',
    category: 'data',
    shadcnComponents: ['Card', 'CardHeader', 'CardContent', 'Progress', 'Badge'],
    radixPrimitives: ['Progress'],
    canvasHeight: 480,
    supportsGrid: true,
    supportsRTL: false,
    tags: ['dashboard', 'kpi', 'charts', 'admin'],
    variants: [
      { id: 'kpi-cards', label: 'KPI Cards', description: 'Stat cards with trend arrows' },
      { id: 'with-charts', label: 'With Charts', description: 'KPI + inline mini charts' },
    ],
  },
  {
    id: 'kanban-board',
    name: 'Kanban Board',
    description: 'Drag-and-drop task board with column lanes',
    category: 'data',
    shadcnComponents: ['Card', 'Badge', 'Avatar', 'Button', 'ScrollArea'],
    radixPrimitives: ['ScrollArea'],
    canvasHeight: 560,
    supportsGrid: false,
    supportsRTL: false,
    tags: ['kanban', 'tasks', 'board', 'workflow'],
    variants: [
      { id: 'three-col', label: '3 Columns', description: 'To-do / In Progress / Done' },
      { id: 'custom-cols', label: 'Custom Columns', description: 'Configurable column count' },
    ],
  },

  // ── FORMS ─────────────────────────────────────────────────────────────────

  {
    id: 'form-auth',
    name: 'Auth Form',
    description: 'Login, register, or reset password form',
    category: 'forms',
    shadcnComponents: ['Form', 'FormField', 'FormItem', 'FormLabel', 'FormControl', 'FormMessage', 'Input', 'Button', 'Card', 'CardContent', 'CardHeader', 'Separator'],
    radixPrimitives: ['Label'],
    canvasHeight: 420,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['auth', 'login', 'register', 'form'],
    variants: [
      { id: 'login', label: 'Login', description: 'Email + password + remember me' },
      { id: 'register', label: 'Register', description: 'Full registration with confirm password' },
      { id: 'magic-link', label: 'Magic Link', description: 'Email only + magic link CTA' },
      { id: 'otp', label: 'OTP Verify', description: '6-digit OTP input' },
    ],
  },
  {
    id: 'form-contact',
    name: 'Contact Form',
    description: 'Multi-field contact or inquiry form',
    category: 'forms',
    shadcnComponents: ['Form', 'FormField', 'Input', 'Textarea', 'Select', 'Button', 'Card'],
    radixPrimitives: ['Select', 'Label'],
    canvasHeight: 460,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['contact', 'form', 'inquiry'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Name + email + message' },
      { id: 'with-select', label: 'With Topic', description: 'Adds topic select field' },
      { id: 'side-by-side', label: 'Split Layout', description: 'Form left + info right' },
    ],
  },
  {
    id: 'form-search',
    name: 'Search Bar',
    description: 'Search input with filters and autocomplete',
    category: 'forms',
    shadcnComponents: ['Input', 'Button', 'Command', 'CommandInput', 'Popover'],
    radixPrimitives: ['Popover'],
    canvasHeight: 64,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['search', 'filter', 'input'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Input + search button' },
      { id: 'command', label: 'Command Palette', description: 'cmdk-style command menu' },
      { id: 'with-filters', label: 'With Filters', description: 'Input + filter dropdowns' },
    ],
  },
  {
    id: 'form-settings',
    name: 'Settings Form',
    description: 'Grouped settings panels with switches and inputs',
    category: 'forms',
    shadcnComponents: ['Form', 'Switch', 'Input', 'Select', 'Separator', 'Button', 'Card'],
    radixPrimitives: ['Switch', 'Separator', 'Select'],
    canvasHeight: 480,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['settings', 'form', 'preferences'],
    variants: [
      { id: 'tabs', label: 'Tabbed', description: 'Settings organized in tabs' },
      { id: 'sections', label: 'Sections', description: 'Stacked sections with separators' },
    ],
  },
  {
    id: 'form-wizard',
    name: 'Multi-Step Form',
    description: 'Wizard-style step-by-step form with progress',
    category: 'forms',
    shadcnComponents: ['Form', 'Progress', 'Button', 'Card', 'Input', 'Select'],
    radixPrimitives: ['Progress'],
    canvasHeight: 520,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['wizard', 'multi-step', 'onboarding', 'form'],
    variants: [
      { id: 'steps-top', label: 'Steps Top', description: 'Step indicator above form' },
      { id: 'steps-side', label: 'Steps Side', description: 'Step list in left sidebar' },
    ],
  },

  // ── MEDIA ─────────────────────────────────────────────────────────────────

  {
    id: 'image-gallery',
    name: 'Image Gallery',
    description: 'Masonry or grid image gallery with lightbox',
    category: 'media',
    shadcnComponents: ['Dialog', 'DialogContent', 'AspectRatio'],
    radixPrimitives: ['Dialog', 'AspectRatio'],
    canvasHeight: 400,
    supportsGrid: true,
    supportsRTL: false,
    tags: ['gallery', 'images', 'lightbox', 'media'],
    variants: [
      { id: 'masonry', label: 'Masonry', description: 'Variable height masonry grid' },
      { id: 'uniform', label: 'Uniform Grid', description: 'Equal-size image tiles' },
      { id: 'featured', label: 'Featured', description: 'Large hero + thumbnail strip' },
    ],
  },
  {
    id: 'video-player',
    name: 'Video Player',
    description: 'Embedded video with play overlay and controls',
    category: 'media',
    shadcnComponents: ['AspectRatio', 'Button'],
    radixPrimitives: ['AspectRatio'],
    canvasHeight: 360,
    supportsGrid: false,
    supportsRTL: false,
    tags: ['video', 'player', 'media', 'embed'],
    variants: [
      { id: 'youtube', label: 'YouTube Embed', description: 'YouTube iframe embed' },
      { id: 'native', label: 'Native Video', description: 'HTML5 video with custom controls' },
      { id: 'thumbnail-play', label: 'Thumbnail + Play', description: 'Image thumbnail with play button overlay' },
    ],
  },

  // ── COMMERCE ──────────────────────────────────────────────────────────────

  {
    id: 'product-listing',
    name: 'Product Listing',
    description: 'E-commerce product grid with filters sidebar',
    category: 'commerce',
    shadcnComponents: ['Card', 'Badge', 'Button', 'Checkbox', 'Slider', 'Select', 'Separator'],
    radixPrimitives: ['Checkbox', 'Slider', 'Select', 'Separator'],
    canvasHeight: 560,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['products', 'shop', 'ecommerce', 'listing'],
    variants: [
      { id: 'grid-with-filters', label: 'Grid + Filters', description: 'Sidebar filters + product grid' },
      { id: 'compact-list', label: 'Compact List', description: 'List view with quick actions' },
    ],
  },
  {
    id: 'pricing-table',
    name: 'Pricing Table',
    description: 'Tiered pricing plans with feature comparison',
    category: 'commerce',
    shadcnComponents: ['Card', 'CardHeader', 'CardContent', 'Badge', 'Button', 'Switch', 'Separator'],
    radixPrimitives: ['Switch', 'Separator'],
    canvasHeight: 480,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['pricing', 'plans', 'tiers', 'saas'],
    variants: [
      { id: 'three-tier', label: '3 Tiers', description: 'Free / Pro / Enterprise' },
      { id: 'toggle', label: 'Monthly/Annual Toggle', description: 'Billing period switch' },
      { id: 'comparison', label: 'Feature Comparison', description: 'Full feature matrix below plans' },
    ],
  },
  {
    id: 'cart-panel',
    name: 'Cart Panel',
    description: 'Shopping cart sheet with items and checkout CTA',
    category: 'commerce',
    shadcnComponents: ['Sheet', 'SheetContent', 'SheetHeader', 'SheetTitle', 'Button', 'Separator', 'ScrollArea'],
    radixPrimitives: ['Sheet', 'ScrollArea', 'Separator'],
    canvasHeight: 520,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['cart', 'checkout', 'ecommerce', 'sheet'],
    variants: [
      { id: 'side-sheet', label: 'Side Sheet', description: 'Slide-in panel from right' },
      { id: 'page', label: 'Page Cart', description: 'Dedicated cart page layout' },
    ],
  },

  // ── LAYOUT ────────────────────────────────────────────────────────────────

  {
    id: 'page-header',
    name: 'Page Header',
    description: 'Section header with title, description, and actions',
    category: 'layout',
    shadcnComponents: ['Button', 'Badge', 'Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 120,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['header', 'page', 'title', 'actions'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Title + subtitle' },
      { id: 'with-actions', label: 'With Actions', description: 'Title + action buttons' },
      { id: 'with-badge', label: 'With Badge', description: 'Title + status badge + actions' },
    ],
  },
  {
    id: 'footer',
    name: 'Footer',
    description: 'Site footer with links, logo, and legal text',
    category: 'layout',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 240,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['footer', 'links', 'legal', 'site'],
    variants: [
      { id: 'minimal', label: 'Minimal', description: 'Logo + copyright' },
      { id: 'multi-column', label: 'Multi Column', description: 'Link columns + newsletter' },
      { id: 'centered', label: 'Centered', description: 'Centered links + social icons' },
    ],
  },
  {
    id: 'divider',
    name: 'Section Divider',
    description: 'Visual separator between content sections',
    category: 'layout',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 48,
    supportsGrid: false,
    supportsRTL: false,
    tags: ['divider', 'separator', 'spacer'],
    variants: [
      { id: 'line', label: 'Line', description: 'Horizontal rule' },
      { id: 'with-label', label: 'With Label', description: 'OR / AND label in center' },
      { id: 'spacer', label: 'Spacer', description: 'Empty vertical space block' },
    ],
  },
  {
    id: 'two-column-layout',
    name: 'Two Column Layout',
    description: 'Split layout wrapper: main content + sidebar',
    category: 'layout',
    shadcnComponents: ['ScrollArea', 'Separator'],
    radixPrimitives: ['ScrollArea'],
    canvasHeight: 400,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['layout', 'two-column', 'sidebar', 'grid'],
    variants: [
      { id: '2-1', label: '2/3 + 1/3', description: 'Main content + narrow sidebar' },
      { id: '1-1', label: '1/2 + 1/2', description: 'Equal split' },
      { id: '1-2', label: '1/3 + 2/3', description: 'Narrow rail + wide content' },
    ],
  },

  // ── FEEDBACK ──────────────────────────────────────────────────────────────

  {
    id: 'empty-state',
    name: 'Empty State',
    description: 'Placeholder when a list or section has no content',
    category: 'feedback',
    shadcnComponents: ['Button'],
    radixPrimitives: [],
    canvasHeight: 280,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['empty', 'zero-state', 'placeholder'],
    variants: [
      { id: 'simple', label: 'Simple', description: 'Icon + message + CTA' },
      { id: 'illustration', label: 'Illustration', description: 'SVG illustration + message' },
    ],
  },
  {
    id: 'loading-state',
    name: 'Loading State',
    description: 'Skeleton loaders and spinners for async content',
    category: 'feedback',
    shadcnComponents: ['Skeleton'],
    radixPrimitives: [],
    canvasHeight: 200,
    supportsGrid: true,
    supportsRTL: false,
    tags: ['loading', 'skeleton', 'spinner', 'async'],
    variants: [
      { id: 'card-skeleton', label: 'Card Skeleton', description: 'Card-shaped loading placeholders' },
      { id: 'table-skeleton', label: 'Table Skeleton', description: 'Table row skeletons' },
      { id: 'page-skeleton', label: 'Page Skeleton', description: 'Full page skeleton layout' },
    ],
  },
  {
    id: 'toast-notifications',
    name: 'Toast Notifications',
    description: 'Non-blocking alert messages for user feedback',
    category: 'feedback',
    shadcnComponents: ['Toast', 'Toaster', 'useToast'],
    radixPrimitives: ['Toast'],
    canvasHeight: 80,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['toast', 'notification', 'alert', 'feedback'],
    variants: [
      { id: 'success', label: 'Success', description: 'Green success message' },
      { id: 'error', label: 'Error', description: 'Red error message' },
      { id: 'with-action', label: 'With Action', description: 'Message + undo/dismiss button' },
    ],
  },
  {
    id: 'alert-banner',
    name: 'Alert Banner',
    description: 'Contextual inline alerts for errors, warnings, info',
    category: 'feedback',
    shadcnComponents: ['Alert', 'AlertTitle', 'AlertDescription'],
    radixPrimitives: [],
    canvasHeight: 80,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['alert', 'warning', 'error', 'info'],
    variants: [
      { id: 'info', label: 'Info', description: 'Informational blue alert' },
      { id: 'warning', label: 'Warning', description: 'Yellow warning alert' },
      { id: 'error', label: 'Error', description: 'Red error alert' },
      { id: 'success', label: 'Success', description: 'Green success alert' },
    ],
  },

  // ── OVERLAY ───────────────────────────────────────────────────────────────

  {
    id: 'modal-dialog',
    name: 'Modal / Dialog',
    description: 'Centered overlay dialog for confirmations and forms',
    category: 'overlay',
    shadcnComponents: ['Dialog', 'DialogContent', 'DialogHeader', 'DialogTitle', 'DialogDescription', 'DialogFooter', 'Button'],
    radixPrimitives: ['Dialog'],
    canvasHeight: 380,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['modal', 'dialog', 'overlay', 'popup'],
    variants: [
      { id: 'confirm', label: 'Confirm', description: 'Action confirmation prompt' },
      { id: 'form', label: 'Form Modal', description: 'Form inside dialog' },
      { id: 'alert', label: 'Alert Dialog', description: 'Destructive action confirmation' },
    ],
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    description: 'Keyboard-driven command menu overlay',
    category: 'overlay',
    shadcnComponents: ['Command', 'CommandDialog', 'CommandInput', 'CommandList', 'CommandEmpty', 'CommandGroup', 'CommandItem'],
    radixPrimitives: ['Dialog'],
    canvasHeight: 360,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['command', 'palette', 'search', 'keyboard'],
    variants: [
      { id: 'default', label: 'Default', description: 'Standard command menu' },
      { id: 'with-groups', label: 'With Groups', description: 'Grouped command sections' },
    ],
  },
  {
    id: 'popover-panel',
    name: 'Popover / Tooltip',
    description: 'Anchored floating panel for contextual content',
    category: 'overlay',
    shadcnComponents: ['Popover', 'PopoverContent', 'PopoverTrigger', 'Tooltip', 'TooltipContent', 'TooltipProvider', 'TooltipTrigger'],
    radixPrimitives: ['Popover', 'Tooltip'],
    canvasHeight: 200,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['popover', 'tooltip', 'floating', 'contextual'],
    variants: [
      { id: 'tooltip', label: 'Tooltip', description: 'Simple hover text tooltip' },
      { id: 'popover', label: 'Popover', description: 'Click-triggered rich content panel' },
    ],
  },
]

export const CATEGORIES: Array<{ id: string; label: string; count: number }> = (() => {
  const categoryCount: Record<string, number> = {}
  COMPONENT_LIBRARY.forEach(b => {
    categoryCount[b.category] = (categoryCount[b.category] || 0) + 1
  })
  return [
    { id: 'all', label: 'All', count: COMPONENT_LIBRARY.length },
    { id: 'navigation', label: 'Navigation', count: categoryCount.navigation || 0 },
    { id: 'hero', label: 'Hero', count: categoryCount.hero || 0 },
    { id: 'content', label: 'Content', count: categoryCount.content || 0 },
    { id: 'data', label: 'Data', count: categoryCount.data || 0 },
    { id: 'forms', label: 'Forms', count: categoryCount.forms || 0 },
    { id: 'media', label: 'Media', count: categoryCount.media || 0 },
    { id: 'commerce', label: 'Commerce', count: categoryCount.commerce || 0 },
    { id: 'layout', label: 'Layout', count: categoryCount.layout || 0 },
    { id: 'feedback', label: 'Feedback', count: categoryCount.feedback || 0 },
    { id: 'overlay', label: 'Overlay', count: categoryCount.overlay || 0 },
  ]
})()
