// ─────────────────────────────────────────────────────────────────────────────
// NEZAM Layout Designer — Shadcn/Radix Component Library
// ─────────────────────────────────────────────────────────────────────────────

import type { LibraryBlock } from './types'

export const COMPONENT_LIBRARY: LibraryBlock[] = [
  // ── NAVIGATION ────────────────────────────────────────────────────────────

  {
    id: 'navbar-top',
    name: 'Top Navbar',
    nameAr: 'شريط التنقل العلوي',
    description: 'Horizontal top navigation with logo, links, and CTA',
    descriptionAr: 'شريط علوي بالعرض فيه اللوجو، لينكات، وزرار طلب الفعل (CTA)',
    category: 'navigation',
    shadcnComponents: ['NavigationMenu', 'Button', 'Sheet'],
    radixPrimitives: ['NavigationMenu'],
    canvasHeight: 64,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['nav', 'header', 'menu'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Logo + links + CTA', descriptionAr: 'لوجو + لينكات + زرار واحد' },
      { id: 'centered', label: 'Centered', labelAr: 'متوسط', description: 'Centered logo with links on both sides', descriptionAr: 'لوجو في النص ولينكات على الجنبين' },
      { id: 'mega-menu', label: 'Mega Menu', labelAr: 'قائمة ضخمة', description: 'Dropdown with rich content panels', descriptionAr: 'قائمة منسدلة فيها تفاصيل كتير' },
    ],
  },
  {
    id: 'sidebar-nav',
    name: 'Sidebar Navigation',
    nameAr: 'التنقل الجانبي',
    description: 'Vertical sidebar with grouped nav items and collapse',
    descriptionAr: 'شريط جانبي طولي فيه عناصر متنظمة وقابل للطي',
    category: 'navigation',
    shadcnComponents: ['ScrollArea', 'Collapsible', 'Badge'],
    radixPrimitives: ['Collapsible'],
    canvasHeight: 500,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['sidebar', 'nav', 'dashboard'],
    variants: [
      { id: 'full', label: 'Full Width', labelAr: 'عرض كامل', description: 'Expanded sidebar with labels', descriptionAr: 'شريط مفرود بالعناوين' },
      { id: 'icon-only', label: 'Icon Only', labelAr: 'أيقونات بس', description: 'Collapsed icon-only rail', descriptionAr: 'شريط مضموم فيه الأيقونات بس' },
      { id: 'grouped', label: 'Grouped', labelAr: 'مجموعات', description: 'Sections with headings', descriptionAr: 'أقسام بعناوين فرعية' },
    ],
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    nameAr: 'مسار التنقل',
    description: 'Hierarchical page trail with dropdown for overflow',
    descriptionAr: 'مسار بيوضح مكانك في الموقع مع قائمة للفائض',
    category: 'navigation',
    shadcnComponents: ['Breadcrumb', 'DropdownMenu'],
    radixPrimitives: ['DropdownMenu'],
    canvasHeight: 40,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['breadcrumb', 'nav', 'trail'],
    variants: [
      { id: 'default', label: 'Default', labelAr: 'افتراضي', description: 'Slash-separated path', descriptionAr: 'مسار مفصول بعلامة /' },
      { id: 'chevron', label: 'Chevron', labelAr: 'سهم', description: 'Chevron separators', descriptionAr: 'مسار مفصول بأسهم' },
      { id: 'collapsed', label: 'Collapsed', labelAr: 'مختصر', description: 'Ellipsis for long paths', descriptionAr: 'نقط للمسارات الطويلة' },
    ],
  },
  {
    id: 'tabs-nav',
    name: 'Tab Navigation',
    nameAr: 'التنقل بالتبويبات',
    description: 'Horizontal tab bar for content switching',
    descriptionAr: 'شريط تبويبات بالعرض للتنقل بين المحتوى',
    category: 'navigation',
    shadcnComponents: ['Tabs', 'TabsList', 'TabsTrigger'],
    radixPrimitives: ['Tabs'],
    canvasHeight: 48,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['tabs', 'nav', 'switch'],
    variants: [
      { id: 'underline', label: 'Underline', labelAr: 'خط سفلي', description: 'Active tab with underline', descriptionAr: 'تبويب نشط بخط تحته' },
      { id: 'pill', label: 'Pill', labelAr: 'كبسولة', description: 'Filled pill active state', descriptionAr: 'تبويب نشط بشكل كبسولة' },
      { id: 'card', label: 'Card', labelAr: 'كارت', description: 'Card-style tabs', descriptionAr: 'تبويبات بشكل كروت' },
    ],
  },
  {
    id: 'pagination',
    name: 'Pagination',
    nameAr: 'الترقيم',
    description: 'Page navigation with prev/next and number buttons',
    descriptionAr: 'التنقل بين الصفحات بالأرقام أو التالي/السابق',
    category: 'navigation',
    shadcnComponents: ['Pagination', 'PaginationContent', 'PaginationItem'],
    radixPrimitives: [],
    canvasHeight: 48,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['pagination', 'pages', 'nav'],
    variants: [
      { id: 'numbered', label: 'Numbered', labelAr: 'أرقام', description: 'All page numbers', descriptionAr: 'كل أرقام الصفحات' },
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Prev / Next only', descriptionAr: 'التالي والسابق بس' },
      { id: 'compact', label: 'Compact', labelAr: 'مدمج', description: 'Current / total with arrows', descriptionAr: 'الصفحة الحالية من الإجمالي' },
    ],
  },

  // ── HERO ──────────────────────────────────────────────────────────────────

  {
    id: 'hero-centered',
    name: 'Centered Hero',
    nameAr: 'هيرو في النص',
    description: 'Full-width hero with headline, sub, and CTA centered',
    descriptionAr: 'قسم رئيسي بالعرض فيه العنوان والوصف والزرار في النص',
    category: 'hero',
    shadcnComponents: ['Button', 'Badge'],
    radixPrimitives: [],
    canvasHeight: 480,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['hero', 'landing', 'headline'],
    variants: [
      { id: 'clean', label: 'Clean', labelAr: 'رايق', description: 'Text + CTA on plain background', descriptionAr: 'نص وزرار على خلفية سادة' },
      { id: 'gradient', label: 'Gradient', labelAr: 'تدرج ألوان', description: 'Gradient background with glow', descriptionAr: 'خلفية متدرجة مع إضاءة' },
      { id: 'with-image', label: 'With Image', labelAr: 'مع صورة', description: 'Centered hero with below-fold image', descriptionAr: 'هيرو في النص وتحته صورة' },
      { id: 'announcement', label: 'Announcement', labelAr: 'إعلان', description: 'Badge pill + headline + CTA', descriptionAr: 'شارة إعلان + عنوان + زرار' },
    ],
  },
  {
    id: 'hero-split',
    name: 'Split Hero',
    nameAr: 'هيرو مقسوم',
    description: 'Two-column hero: text left, visual right',
    descriptionAr: 'قسم رئيسي عمودين: نص على ناحية وصورة/فيديو على التانية',
    category: 'hero',
    shadcnComponents: ['Button', 'AspectRatio', 'Badge'],
    radixPrimitives: ['AspectRatio'],
    canvasHeight: 520,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['hero', 'split', 'two-column'],
    variants: [
      { id: 'text-left', label: 'Text Left', labelAr: 'نص يمين/شمال', description: 'Text on left, image/video on right', descriptionAr: 'نص على ناحية وصورة على التانية' },
      { id: 'text-right', label: 'Text Right', labelAr: 'نص الناحية التانية', description: 'Image on left, text on right', descriptionAr: 'صورة على ناحية ونص على التانية' },
      { id: 'video', label: 'With Video', labelAr: 'مع فيديو', description: 'Embedded video in right pane', descriptionAr: 'فيديو مدمج في القسم' },
    ],
  },
  {
    id: 'hero-fullscreen',
    name: 'Full Screen Hero',
    nameAr: 'هيرو بملء الشاشة',
    description: '100vh hero with overlay content and background',
    descriptionAr: 'قسم رئيسي بياخد طول الشاشة كله مع خلفية ومحتوى',
    category: 'hero',
    shadcnComponents: ['Button'],
    radixPrimitives: [],
    canvasHeight: 600,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['hero', 'fullscreen', 'background'],
    variants: [
      { id: 'dark-overlay', label: 'Dark Overlay', labelAr: 'طبقة غامقة', description: 'Dark gradient over image', descriptionAr: 'تدرج غامق فوق الصورة' },
      { id: 'video-bg', label: 'Video BG', labelAr: 'خلفية فيديو', description: 'Looping video background', descriptionAr: 'فيديو شغال في الخلفية' },
      { id: 'particles', label: 'Particles', labelAr: 'جزيئات متحركة', description: 'Animated particle field', descriptionAr: 'خلفية فيها جزيئات بتتحرك' },
    ],
  },


  // ── CONTENT ───────────────────────────────────────────────────────────────

  {
    id: 'card-grid',
    name: 'Card Grid',
    nameAr: 'شبكة الكروت',
    description: 'Grid of feature/product/article cards',
    descriptionAr: 'شبكة بتعرض كروت للميزات أو المنتجات أو المقالات',
    category: 'content',
    shadcnComponents: ['Card', 'CardHeader', 'CardContent', 'CardFooter', 'Badge', 'Button'],
    radixPrimitives: [],
    canvasHeight: 360,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['cards', 'grid', 'features', 'products'],
    variants: [
      { id: 'feature', label: 'Feature Cards', labelAr: 'كروت الميزات', description: 'Icon + title + description', descriptionAr: 'أيقونة + عنوان + وصف' },
      { id: 'product', label: 'Product Cards', labelAr: 'كروت المنتجات', description: 'Image + price + add to cart', descriptionAr: 'صورة + سعر + زرار الشراء' },
      { id: 'article', label: 'Article Cards', labelAr: 'كروت المقالات', description: 'Thumbnail + meta + title', descriptionAr: 'صورة مصغرة + بيانات + عنوان' },
      { id: 'stat', label: 'Stat Cards', labelAr: 'كروت الإحصائيات', description: 'Large number + label + trend', descriptionAr: 'رقم كبير + عنوان + اتجاه التغيير' },
      { id: 'pricing', label: 'Pricing Cards', labelAr: 'كروت الأسعار', description: 'Plan + features + CTA', descriptionAr: 'خطة + ميزات + زرار اشتراك' },
    ],
  },
  {
    id: 'content-section',
    name: 'Content Section',
    nameAr: 'قسم المحتوى',
    description: 'Rich text section with optional sidebar or image',
    descriptionAr: 'قسم نصي متنسق مع إمكانية إضافة شريط جانبي أو صورة',
    category: 'content',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 320,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['content', 'text', 'article'],
    variants: [
      { id: 'prose', label: 'Prose', labelAr: 'نص مفرود', description: 'Full-width article-style text', descriptionAr: 'نص مقال بعرض كامل' },
      { id: 'two-col', label: 'Two Column', labelAr: 'عمودين', description: 'Content left, sidebar right', descriptionAr: 'محتوى على ناحية وشريط جانبي على التانية' },
      { id: 'with-image', label: 'With Image', labelAr: 'مع صورة', description: 'Text + adjacent image', descriptionAr: 'نص مع صورة جنبه' },
    ],
  },
  {
    id: 'faq-accordion',
    name: 'FAQ / Accordion',
    nameAr: 'الأسئلة الشائعة / أكورديون',
    description: 'Expandable Q&A sections with animated transitions',
    descriptionAr: 'أقسام قابلة للطي للأسئلة والأجوبة مع أنيميشن',
    category: 'content',
    shadcnComponents: ['Accordion', 'AccordionItem', 'AccordionTrigger', 'AccordionContent'],
    radixPrimitives: ['Accordion'],
    canvasHeight: 280,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['faq', 'accordion', 'expandable'],
    variants: [
      { id: 'single', label: 'Single Open', labelAr: 'فتح واحد', description: 'Only one item open at a time', descriptionAr: 'عنصر واحد بس اللي يتفتح في المرة' },
      { id: 'multiple', label: 'Multiple Open', labelAr: 'فتح متعدد', description: 'Multiple items can be open', descriptionAr: 'ممكن تفتح كذا عنصر مع بعض' },
    ],
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
    nameAr: 'آراء العملاء',
    description: 'Customer quotes with avatar and attribution',
    descriptionAr: 'كلام العملاء عن الخدمة مع صورهم وبياناتهم',
    category: 'content',
    shadcnComponents: ['Card', 'Avatar', 'AvatarImage', 'AvatarFallback'],
    radixPrimitives: ['Avatar'],
    canvasHeight: 300,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['testimonials', 'quotes', 'social-proof'],
    variants: [
      { id: 'grid', label: 'Grid', labelAr: 'شبكة', description: '3-column card grid', descriptionAr: 'شبكة كروت من 3 أعمدة' },
      { id: 'carousel', label: 'Carousel', labelAr: 'شريط متحرك', description: 'Sliding carousel', descriptionAr: 'شريط بيتحرك يمين وشمال' },
      { id: 'featured', label: 'Featured', labelAr: 'مميز', description: 'Large centered quote', descriptionAr: 'رأي واحد كبير في النص' },
    ],
  },
  {
    id: 'timeline',
    name: 'Timeline',
    nameAr: 'الجدول الزمني',
    description: 'Vertical or horizontal chronological timeline',
    descriptionAr: 'خط زمني طولي أو عرضي بيعرض الترتيب الزمني للأحداث',
    category: 'content',
    shadcnComponents: ['Badge', 'Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 400,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['timeline', 'history', 'steps'],
    variants: [
      { id: 'vertical', label: 'Vertical', labelAr: 'رأسي', description: 'Top-to-bottom with connector line', descriptionAr: 'من فوق لتحت بخط واصل' },
      { id: 'alternating', label: 'Alternating', labelAr: 'تبادلي', description: 'Left-right alternating layout', descriptionAr: 'توزيع يمين وشمال بالتناوب' },
    ],
  },
  {
    id: 'team-grid',
    name: 'Team Grid',
    nameAr: 'شبكة فريق العمل',
    description: 'Team member cards with photo, name, role, and links',
    descriptionAr: 'كروت أعضاء الفريق مع صورهم وأساميهم وأدوارهم',
    category: 'content',
    shadcnComponents: ['Card', 'Avatar', 'Button'],
    radixPrimitives: ['Avatar'],
    canvasHeight: 340,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['team', 'people', 'about'],
    variants: [
      { id: 'cards', label: 'Cards', labelAr: 'كروت', description: 'Photo + bio card', descriptionAr: 'كارت فيه الصورة والتعريف' },
      { id: 'minimal', label: 'Minimal', labelAr: 'بسيط', description: 'Photo + name + role', descriptionAr: 'صورة + اسم + دور بس' },
    ],
  },
  {
    id: 'cta-banner',
    name: 'CTA Banner',
    nameAr: 'بانر طلب الفعل',
    description: 'Full-width call-to-action strip with headline and button',
    descriptionAr: 'شريط بعرض الشاشة فيه عنوان وزرار لاتخاذ إجراء',
    category: 'content',
    shadcnComponents: ['Button'],
    radixPrimitives: [],
    canvasHeight: 160,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['cta', 'banner', 'conversion'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Text + primary button', descriptionAr: 'نص + زرار رئيسي' },
      { id: 'two-cta', label: 'Two CTAs', labelAr: 'زرارين', description: 'Primary + secondary buttons', descriptionAr: 'زرار رئيسي + زرار فرعي' },
      { id: 'input-cta', label: 'Email CTA', labelAr: 'بريد إلكتروني', description: 'Email input + submit', descriptionAr: 'خانة إيميل + زرار اشتراك' },
    ],
  },
  {
    id: 'logo-bar',
    name: 'Logo Bar',
    nameAr: 'شريط اللوجوهات',
    description: 'Brand logo strip for partners / clients / integrations',
    descriptionAr: 'شريط بيعرض لوجوهات الشركاء أو العملاء',
    category: 'content',
    shadcnComponents: [],
    radixPrimitives: [],
    canvasHeight: 100,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['logos', 'brands', 'partners', 'trust'],
    variants: [
      { id: 'static', label: 'Static', labelAr: 'ثابت', description: 'Fixed grid of logos', descriptionAr: 'شبكة ثابتة من اللوجوهات' },
      { id: 'marquee', label: 'Marquee', labelAr: 'شريط متحرك', description: 'Infinite scrolling logos', descriptionAr: 'لوجوهات بتتحرك بشكل مستمر' },
    ],
  },
  {
    id: 'stats-bar',
    name: 'Stats Bar',
    nameAr: 'شريط الإحصائيات',
    description: 'Horizontal bar of key metrics / numbers',
    descriptionAr: 'شريط عرضي بيعرض الأرقام والنسب المهمة',
    category: 'content',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 140,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['stats', 'metrics', 'numbers'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Number + label', descriptionAr: 'رقم + وصف' },
      { id: 'with-icon', label: 'With Icon', labelAr: 'مع أيقونة', description: 'Icon + number + label', descriptionAr: 'أيقونة + رقم + وصف' },
      { id: 'animated', label: 'Animated', labelAr: 'متحرك', description: 'Count-up animation on scroll', descriptionAr: 'أرقام بتزيد مع السكرول' },
    ],
  },

  // ── DATA ──────────────────────────────────────────────────────────────────

  {
    id: 'data-table',
    name: 'Data Table',
    nameAr: 'جدول بيانات',
    description: 'Sortable, filterable data table with row actions',
    descriptionAr: 'جدول بيانات قابل للترتيب والفلترة مع إجراءات لكل صف',
    category: 'data',
    shadcnComponents: ['Table', 'TableHeader', 'TableBody', 'TableRow', 'TableCell', 'Checkbox', 'Button', 'DropdownMenu', 'Input'],
    radixPrimitives: ['DropdownMenu', 'Checkbox'],
    canvasHeight: 440,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['table', 'data', 'list'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Basic rows and columns', descriptionAr: 'صفوف وأعمدة عادية' },
      { id: 'selectable', label: 'Selectable', labelAr: 'قابل للاختيار', description: 'Checkbox selection + bulk actions', descriptionAr: 'اختيار كذا صف + إجراءات جماعية' },
      { id: 'expandable', label: 'Expandable', labelAr: 'قابل للتوسيع', description: 'Expandable row details', descriptionAr: 'صفوف بتتفتح لعرض تفاصيل أكتر' },
    ],
  },
  {
    id: 'dashboard-grid',
    name: 'Dashboard Grid',
    nameAr: 'شبكة لوحة التحكم',
    description: 'KPI card grid with charts for admin dashboards',
    descriptionAr: 'مجموعة كروت مؤشرات الأداء مع رسوم بيانية',
    category: 'data',
    shadcnComponents: ['Card', 'CardHeader', 'CardContent', 'Progress', 'Badge'],
    radixPrimitives: ['Progress'],
    canvasHeight: 480,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['dashboard', 'kpi', 'charts', 'admin'],
    variants: [
      { id: 'kpi-cards', label: 'KPI Cards', labelAr: 'كروت مؤشرات الأداء', description: 'Stat cards with trend arrows', descriptionAr: 'كروت أرقام مع أسهم اتجاهات' },
      { id: 'with-charts', label: 'With Charts', labelAr: 'مع رسوم بيانية', description: 'KPI + inline mini charts', descriptionAr: 'أرقام مع رسوم بيانية صغيرة' },
    ],
  },
  {
    id: 'kanban-board',
    name: 'Kanban Board',
    nameAr: 'لوحة كانبان',
    description: 'Drag-and-drop task board with column lanes',
    descriptionAr: 'لوحة مهام بالسحب والإفلات متقسمة أعمدة',
    category: 'data',
    shadcnComponents: ['Card', 'Badge', 'Avatar', 'Button', 'ScrollArea'],
    radixPrimitives: ['ScrollArea'],
    canvasHeight: 560,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['kanban', 'tasks', 'board', 'workflow'],
    variants: [
      { id: 'three-col', label: '3 Columns', labelAr: '3 أعمدة', description: 'To-do / In Progress / Done', descriptionAr: 'للتنفيذ / قيد العمل / تم' },
      { id: 'custom-cols', label: 'Custom Columns', labelAr: 'أعمدة مخصصة', description: 'Configurable column count', descriptionAr: 'أعمدة زي ما تحب' },
    ],
  },


  // ── FORMS ─────────────────────────────────────────────────────────────────

  {
    id: 'form-auth',
    name: 'Auth Form',
    nameAr: 'نموذج الدخول والتسجيل',
    description: 'Login, register, or reset password form',
    descriptionAr: 'نموذج دخول، تسجيل، أو إعادة تعيين كلمة السر',
    category: 'forms',
    shadcnComponents: ['Form', 'FormField', 'FormItem', 'FormLabel', 'FormControl', 'FormMessage', 'Input', 'Button', 'Card', 'CardContent', 'CardHeader', 'Separator'],
    radixPrimitives: ['Label'],
    canvasHeight: 420,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['auth', 'login', 'register', 'form'],
    variants: [
      { id: 'login', label: 'Login', labelAr: 'تسجيل دخول', description: 'Email + password + remember me', descriptionAr: 'إيميل + كلمة سر + تذكرني' },
      { id: 'register', label: 'Register', labelAr: 'تسجيل جديد', description: 'Full registration with confirm password', descriptionAr: 'تسجيل كامل مع تأكيد كلمة السر' },
      { id: 'magic-link', label: 'Magic Link', labelAr: 'لينك سحري', description: 'Email only + magic link CTA', descriptionAr: 'إيميل بس + زرار اللينك السحري' },
      { id: 'otp', label: 'OTP Verify', labelAr: 'كود التحقق', description: '6-digit OTP input', descriptionAr: 'إدخال كود التحقق (6 أرقام)' },
    ],
  },
  {
    id: 'form-contact',
    name: 'Contact Form',
    nameAr: 'نموذج تواصل',
    description: 'Multi-field contact or inquiry form',
    descriptionAr: 'نموذج تواصل أو استفسار فيه خانات كتير',
    category: 'forms',
    shadcnComponents: ['Form', 'FormField', 'Input', 'Textarea', 'Select', 'Button', 'Card'],
    radixPrimitives: ['Select', 'Label'],
    canvasHeight: 460,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['contact', 'form', 'inquiry'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Name + email + message', descriptionAr: 'اسم + إيميل + رسالة' },
      { id: 'with-select', label: 'With Topic', labelAr: 'مع موضوع', description: 'Adds topic select field', descriptionAr: 'بيضيف خانة لاختيار الموضوع' },
      { id: 'side-by-side', label: 'Split Layout', labelAr: 'تخطيط مقسوم', description: 'Form left + info right', descriptionAr: 'نموذج على ناحية ومعلومات على التانية' },
    ],
  },
  {
    id: 'form-search',
    name: 'Search Bar',
    nameAr: 'شريط بحث',
    description: 'Search input with filters and autocomplete',
    descriptionAr: 'خانة بحث مع فلاتر واقتراحات تلقائية',
    category: 'forms',
    shadcnComponents: ['Input', 'Button', 'Command', 'CommandInput', 'Popover'],
    radixPrimitives: ['Popover'],
    canvasHeight: 64,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['search', 'filter', 'input'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Input + search button', descriptionAr: 'خانة بحث + زرار' },
      { id: 'command', label: 'Command Palette', labelAr: 'لوحة أوامر', description: 'cmdk-style command menu', descriptionAr: 'قائمة أوامر سريعة' },
      { id: 'with-filters', label: 'With Filters', labelAr: 'مع فلاتر', description: 'Input + filter dropdowns', descriptionAr: 'خانة بحث + قوائم فلترة' },
    ],
  },
  {
    id: 'form-settings',
    name: 'Settings Form',
    nameAr: 'نموذج إعدادات',
    description: 'Grouped settings panels with switches and inputs',
    descriptionAr: 'لوحات إعدادات متنظمة فيها زراير وخانات',
    category: 'forms',
    shadcnComponents: ['Form', 'Switch', 'Input', 'Select', 'Separator', 'Button', 'Card'],
    radixPrimitives: ['Switch', 'Separator', 'Select'],
    canvasHeight: 480,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['settings', 'form', 'preferences'],
    variants: [
      { id: 'tabs', label: 'Tabbed', labelAr: 'تبويبات', description: 'Settings organized in tabs', descriptionAr: 'إعدادات متقسمة لتبويبات' },
      { id: 'sections', label: 'Sections', labelAr: 'أقسام', description: 'Stacked sections with separators', descriptionAr: 'أقسام فوق بعض بيفصلها فواصل' },
    ],
  },
  {
    id: 'form-wizard',
    name: 'Multi-Step Form',
    nameAr: 'نموذج متعدد الخطوات',
    description: 'Wizard-style step-by-step form with progress',
    descriptionAr: 'نموذج بيمشي معاك خطوة بخطوة مع شريط تقدم',
    category: 'forms',
    shadcnComponents: ['Form', 'Progress', 'Button', 'Card', 'Input', 'Select'],
    radixPrimitives: ['Progress'],
    canvasHeight: 520,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['wizard', 'multi-step', 'onboarding', 'form'],
    variants: [
      { id: 'steps-top', label: 'Steps Top', labelAr: 'خطوات فوق', description: 'Step indicator above form', descriptionAr: 'مؤشر الخطوات فوق النموذج' },
      { id: 'steps-side', label: 'Steps Side', labelAr: 'خطوات على الجنب', description: 'Step list in left sidebar', descriptionAr: 'قايمة الخطوات في شريط جانبي' },
    ],
  },

  // ── MEDIA ─────────────────────────────────────────────────────────────────

  {
    id: 'image-gallery',
    name: 'Image Gallery',
    nameAr: 'معرض صور',
    description: 'Masonry or grid image gallery with lightbox',
    descriptionAr: 'معرض صور بطرق عرض مختلفة مع ميزة التكبير',
    category: 'media',
    shadcnComponents: ['Dialog', 'DialogContent', 'AspectRatio'],
    radixPrimitives: ['Dialog', 'AspectRatio'],
    canvasHeight: 400,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['gallery', 'images', 'lightbox', 'media'],
    variants: [
      { id: 'masonry', label: 'Masonry', labelAr: 'توزيع حر', description: 'Variable height masonry grid', descriptionAr: 'شبكة صور بأطوال مختلفة' },
      { id: 'uniform', label: 'Uniform Grid', labelAr: 'شبكة منتظمة', description: 'Equal-size image tiles', descriptionAr: 'صور متساوية في الحجم' },
      { id: 'featured', label: 'Featured', labelAr: 'صورة مميزة', description: 'Large hero + thumbnail strip', descriptionAr: 'صورة كبيرة وجنبها صور صغيرة' },
    ],
  },
  {
    id: 'video-player',
    name: 'Video Player',
    nameAr: 'مشغل فيديو',
    description: 'Embedded video with play overlay and controls',
    descriptionAr: 'فيديو مدمج مع أزرار تحكم',
    category: 'media',
    shadcnComponents: ['AspectRatio', 'Button'],
    radixPrimitives: ['AspectRatio'],
    canvasHeight: 360,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['video', 'player', 'media', 'embed'],
    variants: [
      { id: 'youtube', label: 'YouTube Embed', labelAr: 'يوتيوب', description: 'YouTube iframe embed', descriptionAr: 'فيديو مدمج من يوتيوب' },
      { id: 'native', label: 'Native Video', labelAr: 'فيديو مباشر', description: 'HTML5 video with custom controls', descriptionAr: 'فيديو مباشر مع أزرار تحكم' },
      { id: 'thumbnail-play', label: 'Thumbnail + Play', labelAr: 'صورة تشغيل', description: 'Image thumbnail with play button overlay', descriptionAr: 'صورة معاينة وعليها زرار تشغيل' },
    ],
  },

  // ── COMMERCE ──────────────────────────────────────────────────────────────

  {
    id: 'product-listing',
    name: 'Product Listing',
    nameAr: 'قائمة منتجات',
    description: 'E-commerce product grid with filters sidebar',
    descriptionAr: 'شبكة منتجات مع شريط فلاتر جانبي',
    category: 'commerce',
    shadcnComponents: ['Card', 'Badge', 'Button', 'Checkbox', 'Slider', 'Select', 'Separator'],
    radixPrimitives: ['Checkbox', 'Slider', 'Select', 'Separator'],
    canvasHeight: 560,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['products', 'shop', 'ecommerce', 'listing'],
    variants: [
      { id: 'grid-with-filters', label: 'Grid + Filters', labelAr: 'شبكة + فلاتر', description: 'Sidebar filters + product grid', descriptionAr: 'فلاتر جانبية + شبكة منتجات' },
      { id: 'compact-list', label: 'Compact List', labelAr: 'قائمة مدمجة', description: 'List view with quick actions', descriptionAr: 'عرض قائمة مع إجراءات سريعة' },
    ],
  },
  {
    id: 'pricing-table',
    name: 'Pricing Table',
    nameAr: 'جدول أسعار',
    description: 'Tiered pricing plans with feature comparison',
    descriptionAr: 'خطط أسعار مختلفة مع مقارنة للميزات',
    category: 'commerce',
    shadcnComponents: ['Card', 'CardHeader', 'CardContent', 'Badge', 'Button', 'Switch', 'Separator'],
    radixPrimitives: ['Switch', 'Separator'],
    canvasHeight: 480,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['pricing', 'plans', 'tiers', 'saas'],
    variants: [
      { id: 'three-tier', label: '3 Tiers', labelAr: '3 مستويات', description: 'Free / Pro / Enterprise', descriptionAr: 'مجاني / احترافي / شركات' },
      { id: 'toggle', label: 'Monthly/Annual Toggle', labelAr: 'تبديل شهري/سنوي', description: 'Billing period switch', descriptionAr: 'زرار للتحويل بين الدفع الشهري والسنوي' },
      { id: 'comparison', label: 'Feature Comparison', labelAr: 'مقارنة ميزات', description: 'Full feature matrix below plans', descriptionAr: 'جدول مقارنة كامل تحت الخطط' },
    ],
  },
  {
    id: 'cart-panel',
    name: 'Cart Panel',
    nameAr: 'لوحة السلة',
    description: 'Shopping cart sheet with items and checkout CTA',
    descriptionAr: 'شريط جانبي للسلة فيه المنتجات وزرار الدفع',
    category: 'commerce',
    shadcnComponents: ['Sheet', 'SheetContent', 'SheetHeader', 'SheetTitle', 'Button', 'Separator', 'ScrollArea'],
    radixPrimitives: ['Sheet', 'ScrollArea', 'Separator'],
    canvasHeight: 520,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['cart', 'checkout', 'ecommerce', 'sheet'],
    variants: [
      { id: 'side-sheet', label: 'Side Sheet', labelAr: 'لوحة جانبية', description: 'Slide-in panel from right', descriptionAr: 'لوحة بتظهر من الجنب' },
      { id: 'page', label: 'Page Cart', labelAr: 'صفحة السلة', description: 'Dedicated cart page layout', descriptionAr: 'تخطيط لصفحة السلة كاملة' },
    ],
  },

  // ── LAYOUT ────────────────────────────────────────────────────────────────

  {
    id: 'page-header',
    name: 'Page Header',
    nameAr: 'عنوان الصفحة',
    description: 'Section header with title, description, and actions',
    descriptionAr: 'رأس الصفحة فيه العنوان والوصف وزراير الإجراءات',
    category: 'layout',
    shadcnComponents: ['Button', 'Badge', 'Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 120,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['header', 'page', 'title', 'actions'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Title + subtitle', descriptionAr: 'عنوان + عنوان فرعي' },
      { id: 'with-actions', label: 'With Actions', labelAr: 'مع إجراءات', description: 'Title + action buttons', descriptionAr: 'عنوان + أزرار إجراءات' },
      { id: 'with-badge', label: 'With Badge', labelAr: 'مع شارة', description: 'Title + status badge + actions', descriptionAr: 'عنوان + شارة حالة + زراير' },
    ],
  },
  {
    id: 'footer',
    name: 'Footer',
    nameAr: 'تذييل الصفحة',
    description: 'Site footer with links, logo, and legal text',
    descriptionAr: 'آخر الصفحة فيه لينكات واللوجو ومعلومات قانونية',
    category: 'layout',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 240,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['footer', 'links', 'legal', 'site'],
    variants: [
      { id: 'minimal', label: 'Minimal', labelAr: 'بسيط', description: 'Logo + copyright', descriptionAr: 'لوجو + حقوق النشر' },
      { id: 'multi-column', label: 'Multi Column', labelAr: 'أعمدة كتير', description: 'Link columns + newsletter', descriptionAr: 'أعمدة لينكات + نشرة بريدية' },
      { id: 'centered', label: 'Centered', labelAr: 'متوسط', description: 'Centered links + social icons', descriptionAr: 'لينكات في النص + أيقونات تواص' },
    ],
  },
  {
    id: 'divider',
    name: 'Section Divider',
    nameAr: 'فاصل',
    description: 'Visual separator between content sections',
    descriptionAr: 'فاصل بصري بين أقسام المحتوى',
    category: 'layout',
    shadcnComponents: ['Separator'],
    radixPrimitives: ['Separator'],
    canvasHeight: 48,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['divider', 'separator', 'spacer'],
    variants: [
      { id: 'line', label: 'Line', labelAr: 'خط', description: 'Horizontal rule', descriptionAr: 'خط عرضي' },
      { id: 'with-label', label: 'With Label', labelAr: 'مع عنوان', description: 'OR / AND label in center', descriptionAr: 'عنوان في نص الخط' },
      { id: 'spacer', label: 'Spacer', labelAr: 'مساحة', description: 'Empty vertical space block', descriptionAr: 'مساحة فاضية بين الأقسام' },
    ],
  },
  {
    id: 'two-column-layout',
    name: 'Two Column Layout',
    nameAr: 'تخطيط عمودين',
    description: 'Split layout wrapper: main content + sidebar',
    descriptionAr: 'توزيع للمحتوى: قسم أساسي وشريط جانبي',
    category: 'layout',
    shadcnComponents: ['ScrollArea', 'Separator'],
    radixPrimitives: ['ScrollArea'],
    canvasHeight: 400,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['layout', 'two-column', 'sidebar', 'grid'],
    variants: [
      { id: '2-1', label: '2/3 + 1/3', labelAr: '2/3 + 1/3', description: 'Main content + narrow sidebar', descriptionAr: 'محتوى أساسي + شريط جانبي رفيع' },
      { id: '1-1', label: '1/2 + 1/2', labelAr: '1/2 + 1/2', description: 'Equal split', descriptionAr: 'تقسيم بالتساوي' },
      { id: '1-2', label: '1/3 + 2/3', labelAr: '1/3 + 2/3', description: 'Narrow rail + wide content', descriptionAr: 'شريط رفيع + محتوى عريض' },
    ],
  },

  // ── FEEDBACK ──────────────────────────────────────────────────────────────

  {
    id: 'empty-state',
    name: 'Empty State',
    nameAr: 'حالة فاضية',
    description: 'Placeholder when a list or section has no content',
    descriptionAr: 'شكل بيظهر لما ميكونش فيه محتوى في القسم',
    category: 'feedback',
    shadcnComponents: ['Button'],
    radixPrimitives: [],
    canvasHeight: 280,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['empty', 'zero-state', 'placeholder'],
    variants: [
      { id: 'simple', label: 'Simple', labelAr: 'بسيط', description: 'Icon + message + CTA', descriptionAr: 'أيقونة + رسالة + زرار' },
      { id: 'illustration', label: 'Illustration', labelAr: 'رسم توضيحي', description: 'SVG illustration + message', descriptionAr: 'رسمة توضيحية + رسالة' },
    ],
  },
  {
    id: 'loading-state',
    name: 'Loading State',
    nameAr: 'حالة تحميل',
    description: 'Skeleton loaders and spinners for async content',
    descriptionAr: 'أشكال مؤقتة بتظهر لحد ما المحتوى يتحمل',
    category: 'feedback',
    shadcnComponents: ['Skeleton'],
    radixPrimitives: [],
    canvasHeight: 200,
    supportsGrid: true,
    supportsRTL: true,
    tags: ['loading', 'skeleton', 'spinner', 'async'],
    variants: [
      { id: 'card-skeleton', label: 'Card Skeleton', labelAr: 'هيكل كارت', description: 'Card-shaped loading placeholders', descriptionAr: 'أشكال كروت مؤقتة' },
      { id: 'table-skeleton', label: 'Table Skeleton', labelAr: 'هيكل جدول', description: 'Table row skeletons', descriptionAr: 'صفوف جدول مؤقتة' },
      { id: 'page-skeleton', label: 'Page Skeleton', labelAr: 'هيكل صفحة', description: 'Full page skeleton layout', descriptionAr: 'تخطيط صفحة كاملة مؤقت' },
    ],
  },
  {
    id: 'toast-notifications',
    name: 'Toast Notifications',
    nameAr: 'تنبيهات سريعة',
    description: 'Non-blocking alert messages for user feedback',
    descriptionAr: 'رسايل تنبيه بتظهر وتختفي من غير ما تعطل المستخدم',
    category: 'feedback',
    shadcnComponents: ['Toast', 'Toaster', 'useToast'],
    radixPrimitives: ['Toast'],
    canvasHeight: 80,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['toast', 'notification', 'alert', 'feedback'],
    variants: [
      { id: 'success', label: 'Success', labelAr: 'نجاح', description: 'Green success message', descriptionAr: 'رسالة نجاح خضراء' },
      { id: 'error', label: 'Error', labelAr: 'خطأ', description: 'Red error message', descriptionAr: 'رسالة خطأ حمراء' },
      { id: 'with-action', label: 'With Action', labelAr: 'مع إجراء', description: 'Message + undo/dismiss button', descriptionAr: 'رسالة + زرار تراجع' },
    ],
  },
  {
    id: 'alert-banner',
    name: 'Alert Banner',
    nameAr: 'بانر تنبيه',
    description: 'Contextual inline alerts for errors, warnings, info',
    descriptionAr: 'تنبيهات بتظهر وسط المحتوى للأخطاء أو التحذيرات',
    category: 'feedback',
    shadcnComponents: ['Alert', 'AlertTitle', 'AlertDescription'],
    radixPrimitives: [],
    canvasHeight: 80,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['alert', 'warning', 'error', 'info'],
    variants: [
      { id: 'info', label: 'Info', labelAr: 'معلومات', description: 'Informational blue alert', descriptionAr: 'تنبيه معلومات أزرق' },
      { id: 'warning', label: 'Warning', labelAr: 'تحذير', description: 'Yellow warning alert', descriptionAr: 'تنبيه تحذير أصفر' },
      { id: 'error', label: 'Error', labelAr: 'خطأ', description: 'Red error alert', descriptionAr: 'تنبيه خطأ أحمر' },
      { id: 'success', label: 'Success', labelAr: 'نجاح', description: 'Green success alert', descriptionAr: 'تنبيه نجاح أخضر' },
    ],
  },

  // ── OVERLAY ───────────────────────────────────────────────────────────────

  {
    id: 'modal-dialog',
    name: 'Modal / Dialog',
    nameAr: 'نافذة منبثقة',
    description: 'Centered overlay dialog for confirmations and forms',
    descriptionAr: 'نافذة بتظهر فوق المحتوى للتأكيد أو النماذج',
    category: 'overlay',
    shadcnComponents: ['Dialog', 'DialogContent', 'DialogHeader', 'DialogTitle', 'DialogDescription', 'DialogFooter', 'Button'],
    radixPrimitives: ['Dialog'],
    canvasHeight: 380,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['modal', 'dialog', 'overlay', 'popup'],
    variants: [
      { id: 'confirm', label: 'Confirm', labelAr: 'تأكيد', description: 'Action confirmation prompt', descriptionAr: 'رسالة لتأكيد الإجراء' },
      { id: 'form', label: 'Form Modal', labelAr: 'نافذة نموذج', description: 'Form inside dialog', descriptionAr: 'نموذج إدخال بيانات جوه النافذة' },
      { id: 'alert', label: 'Alert Dialog', labelAr: 'تنبيه خطير', description: 'Destructive action confirmation', descriptionAr: 'تأكيد لإجراء لا يمكن الرجوع فيه' },
    ],
  },
  {
    id: 'command-palette',
    name: 'Command Palette',
    nameAr: 'لوحة أوامر',
    description: 'Keyboard-driven command menu overlay',
    descriptionAr: 'قائمة أوامر سريعة بتشتغل بالكيبورد',
    category: 'overlay',
    shadcnComponents: ['Command', 'CommandDialog', 'CommandInput', 'CommandList', 'CommandEmpty', 'CommandGroup', 'CommandItem'],
    radixPrimitives: ['Dialog'],
    canvasHeight: 360,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['command', 'palette', 'search', 'keyboard'],
    variants: [
      { id: 'default', label: 'Default', labelAr: 'افتراضي', description: 'Standard command menu', descriptionAr: 'قائمة أوامر عادية' },
      { id: 'with-groups', label: 'With Groups', labelAr: 'مع مجموعات', description: 'Grouped command sections', descriptionAr: 'أوامر متنظمة في مجموعات' },
    ],
  },
  {
    id: 'popover-panel',
    name: 'Popover / Tooltip',
    nameAr: 'نافذة معلومات',
    description: 'Anchored floating panel for contextual content',
    descriptionAr: 'لوحة بتظهر فوق عنصر معين لعرض محتوى إضافي',
    category: 'overlay',
    shadcnComponents: ['Popover', 'PopoverContent', 'PopoverTrigger', 'Tooltip', 'TooltipContent', 'TooltipProvider', 'TooltipTrigger'],
    radixPrimitives: ['Popover', 'Tooltip'],
    canvasHeight: 200,
    supportsGrid: false,
    supportsRTL: true,
    tags: ['popover', 'tooltip', 'floating', 'contextual'],
    variants: [
      { id: 'tooltip', label: 'Tooltip', labelAr: 'تلميح', description: 'Simple hover text tooltip', descriptionAr: 'نص تلميح بسيط بيظهر عند الوقوف بالماوس' },
      { id: 'popover', label: 'Popover', labelAr: 'لوحة معلومات', description: 'Click-triggered rich content panel', descriptionAr: 'لوحة فيها محتوى غني بتظهر عند الضغط' },
    ],
  },
]

export const CATEGORIES: Array<{ id: string; label: string; labelAr: string; count: number }> = (() => {
  const categoryCount: Record<string, number> = {}
  COMPONENT_LIBRARY.forEach(b => {
    categoryCount[b.category] = (categoryCount[b.category] || 0) + 1
  })
  return [
    { id: 'all', label: 'All', labelAr: 'الكل', count: COMPONENT_LIBRARY.length },
    { id: 'navigation', label: 'Navigation', labelAr: 'التنقل', count: categoryCount.navigation || 0 },
    { id: 'hero', label: 'Hero', labelAr: 'هيرو', count: categoryCount.hero || 0 },
    { id: 'content', label: 'Content', labelAr: 'المحتوى', count: categoryCount.content || 0 },
    { id: 'data', label: 'Data', labelAr: 'البيانات', count: categoryCount.data || 0 },
    { id: 'forms', label: 'Forms', labelAr: 'النماذج', count: categoryCount.forms || 0 },
    { id: 'media', label: 'Media', labelAr: 'الوسائط', count: categoryCount.media || 0 },
    { id: 'commerce', label: 'Commerce', labelAr: 'التجارة', count: categoryCount.commerce || 0 },
    { id: 'layout', label: 'Layout', labelAr: 'التخطيط', count: categoryCount.layout || 0 },
    { id: 'feedback', label: 'Feedback', labelAr: 'التغذية الراجعة', count: categoryCount.feedback || 0 },
    { id: 'overlay', label: 'Overlay', labelAr: 'النوافذ', count: categoryCount.overlay || 0 },
  ]
})()
