#!/usr/bin/env node

const args = process.argv.slice(2)
console.log(`[Nezam CLI] Running with args:`, args.join(' '))

const command = args[0]

if (command === 'sitemap') {
  console.log(`[OK] Sitemap node created and linked.`)
} else {
  console.log(`[OK] Command executed successfully.`)
}
