#!/usr/bin/env bash
# Export root DESIGN.md (+ optional wireframes lock) for Stitch DESIGN.md CLI workflow.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
DESIGN="${DESIGN_MD:-$ROOT/DESIGN.md}"
OUT="${STITCH_EXPORT_DIR:-$ROOT/docs/plan/design/stitch-export}"
WIREFRAMES="${WIREFRAMES_LOCK:-$ROOT/wireframes_locked.json}"

mkdir -p "$OUT"

if [[ ! -f "$DESIGN" ]]; then
  echo "export-stitch-design-md: missing $DESIGN"
  exit 1
fi

cp "$DESIGN" "$OUT/DESIGN.md"
echo "Copied DESIGN.md -> $OUT/DESIGN.md"

if [[ -f "$WIREFRAMES" ]]; then
  cp "$WIREFRAMES" "$OUT/wireframes_locked.json"
  echo "Copied wireframes_locked.json -> $OUT/wireframes_locked.json"
fi

cat > "$OUT/README.md" <<'EOF'
# Stitch DESIGN.md export

Generated by `.nezam/core/scripts/design/export-stitch-design-md.sh`.

1. Review `DESIGN.md` in this folder.
2. If [Stitch DESIGN.md CLI](https://stitch.withgoogle.com/docs/design-md/cli/) is installed locally, run Google's export/validate commands against this bundle.
3. Keep repository root `DESIGN.md` as the SDD contract; treat this folder as a portable handoff snapshot.

See `docs/plan/design/DESIGN_SKILLS.md` and skill `@.cursor/skills/design/stitch-design-taste/SKILL.md`.
EOF

echo "export-stitch-design-md: done -> $OUT"
echo "Optional: npx (stitch CLI per Google docs) validate $OUT/DESIGN.md"
